# 01_create_infra.ps1
# Creates EC2 (t3.micro), RDS PostgreSQL (db.t3.micro), Security Groups,
# and allocates an Elastic IP for the Ubertool backend MVP.
#
# Usage: .\01_create_infra.ps1

$ErrorActionPreference = "Stop"

. "$PSScriptRoot\Load-Env.ps1"
Import-Env "$PSScriptRoot\config.env"

Write-Host "========================================"
Write-Host " Ubertool MVP - AWS Infrastructure Setup"
Write-Host "========================================"
Write-Host "Region  : $AWS_REGION"
Write-Host "App Name: $APP_NAME"
Write-Host ""

# 1. Default VPC
Write-Host "[1/9] Fetching default VPC..."
$VPC_ID = $(aws ec2 describe-vpcs --filters "Name=isDefault,Values=true" --query "Vpcs[0].VpcId" --output text --region $AWS_REGION)
Write-Host "      VPC ID: $VPC_ID"

$SUBNET_IDS = $(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$VPC_ID" --query "Subnets[*].SubnetId" --output text --region $AWS_REGION) -split '\s+'
$SUBNET_1   = $SUBNET_IDS[0]
$SUBNET_2   = $SUBNET_IDS[1]
$EC2_SUBNET = $SUBNET_IDS[0]
Write-Host "      Subnets: $SUBNET_1, $SUBNET_2"

# 2. EC2 Security Group
Write-Host "[2/9] Creating EC2 security group..."
$EC2_SG_ID = $(aws ec2 create-security-group --group-name "$APP_NAME-ec2-sg" --description "Ubertool EC2 SSH and gRPC" --vpc-id $VPC_ID --query "GroupId" --output text --region $AWS_REGION)
Write-Host "      EC2 SG: $EC2_SG_ID"

aws ec2 authorize-security-group-ingress --group-id $EC2_SG_ID --protocol tcp --port 22 --cidr "0.0.0.0/0" --region $AWS_REGION | Out-Null
aws ec2 authorize-security-group-ingress --group-id $EC2_SG_ID --protocol tcp --port 80 --cidr "0.0.0.0/0" --region $AWS_REGION | Out-Null
aws ec2 authorize-security-group-ingress --group-id $EC2_SG_ID --protocol tcp --port $GRPC_PORT --cidr "0.0.0.0/0" --region $AWS_REGION | Out-Null
if ($GRPC_PORT -ne "443") {
    aws ec2 authorize-security-group-ingress --group-id $EC2_SG_ID --protocol tcp --port 443 --cidr "0.0.0.0/0" --region $AWS_REGION | Out-Null
}

# 3. RDS Security Group
Write-Host "[3/9] Creating RDS security group..."
$RDS_SG_ID = $(aws ec2 create-security-group --group-name "$APP_NAME-rds-sg" --description "Ubertool RDS PostgreSQL from EC2 only" --vpc-id $VPC_ID --query "GroupId" --output text --region $AWS_REGION)
Write-Host "      RDS SG: $RDS_SG_ID"

aws ec2 authorize-security-group-ingress --group-id $RDS_SG_ID --protocol tcp --port 5432 --source-group $EC2_SG_ID --region $AWS_REGION | Out-Null

# 4. RDS Subnet Group
Write-Host "[4/9] Creating RDS subnet group..."
aws rds create-db-subnet-group --db-subnet-group-name "$APP_NAME-subnet-group" --db-subnet-group-description "Ubertool RDS subnet group" --subnet-ids $SUBNET_1 $SUBNET_2 --region $AWS_REGION | Out-Null
Write-Host "      Subnet group created."

# 5. RDS Instance
Write-Host "[5/9] Creating RDS db.t3.micro PostgreSQL instance (this takes ~5 min)..."
aws rds create-db-instance --db-instance-identifier "$APP_NAME-db" --db-instance-class db.t3.micro --engine postgres --engine-version "17.6" --master-username $DB_USER --master-user-password $DB_PASSWORD --db-name $DB_NAME --allocated-storage 20 --storage-type gp2 --no-publicly-accessible --vpc-security-group-ids $RDS_SG_ID --db-subnet-group-name "$APP_NAME-subnet-group" --backup-retention-period 0 --no-multi-az --region $AWS_REGION | Out-Null
Write-Host "      RDS instance creation initiated."

# 6. EC2 Instance
Write-Host "[6/9] Launching EC2 t3.micro instance..."
$INSTANCE_ID = $(aws ec2 run-instances --image-id $AMI_ID --instance-type t3.micro --key-name $KEY_PAIR_NAME --security-group-ids $EC2_SG_ID --subnet-id $EC2_SUBNET --user-data "file://$PSScriptRoot/ec2_userdata.sh" --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$APP_NAME-api}]" --query "Instances[0].InstanceId" --output text --region $AWS_REGION)
Write-Host "      Instance ID: $INSTANCE_ID"

# 7. Wait for EC2 running
Write-Host "[7/9] Waiting for EC2 to reach running state..."
aws ec2 wait instance-running --instance-ids $INSTANCE_ID --region $AWS_REGION
Write-Host "      EC2 instance is running."

# 8. Elastic IP
Write-Host "[8/9] Allocating and associating Elastic IP..."
$ALLOC_ID   = $(aws ec2 allocate-address --domain vpc --query "AllocationId" --output text --region $AWS_REGION)
aws ec2 associate-address --instance-id $INSTANCE_ID --allocation-id $ALLOC_ID --region $AWS_REGION | Out-Null
$ELASTIC_IP = $(aws ec2 describe-addresses --allocation-ids $ALLOC_ID --query "Addresses[0].PublicIp" --output text --region $AWS_REGION)
Write-Host "      Elastic IP: $ELASTIC_IP"

# 9. Save state file
Write-Host "[9/9] Writing infra state to infra_state.env..."
$stateContent = @(
    "# Auto-generated by 01_create_infra.ps1 - do not edit manually",
    "INSTANCE_ID=$INSTANCE_ID",
    "ELASTIC_IP=$ELASTIC_IP",
    "ALLOC_ID=$ALLOC_ID",
    "EC2_SG_ID=$EC2_SG_ID",
    "RDS_SG_ID=$RDS_SG_ID",
    "VPC_ID=$VPC_ID"
)
$stateContent | Set-Content "$PSScriptRoot\infra_state.env" -Encoding ASCII

Write-Host ""
Write-Host "========================================"
Write-Host " Infrastructure created successfully!"
Write-Host "========================================"
Write-Host ""
Write-Host "  EC2 Instance ID : $INSTANCE_ID"
Write-Host "  Elastic IP      : $ELASTIC_IP"
Write-Host "  RDS identifier  : $APP_NAME-db (still initializing)"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Wait ~5 min for RDS, then run: .\02_init_db.ps1"
Write-Host "  2. SSH test: ssh -i $SSH_KEY_PATH ubuntu@$ELASTIC_IP"
Write-Host ""
Write-Host "  Check RDS status:"
Write-Host "  aws rds describe-db-instances --db-instance-identifier $APP_NAME-db --query DBInstances[0].DBInstanceStatus --output text"