#!/usr/bin/env bash
# =============================================================================
# 04_deploy.sh
# Cross-compiles the Go gRPC binary for Linux/amd64, uploads it to EC2,
# writes the environment config, installs the systemd service, and starts it.
#
# Run this script for every code update (re-deployment).
#
# Usage:
#   ./04_deploy.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/config.env"
source "${SCRIPT_DIR}/infra_state.env"

PROJECT_ROOT="${SCRIPT_DIR}/../.."
BINARY_NAME="ubertool-api"
BUILD_DIR="${SCRIPT_DIR}/build"

echo "========================================"
echo " Ubertool MVP — Build & Deploy"
echo "========================================"
echo "  Target  : ubuntu@${ELASTIC_IP}"
echo "  Binary  : ${BINARY_NAME}"
echo ""

# ── 1. Build Go binary for Linux amd64 ───────────────────────────────────────
echo "[1/6] Building Go binary (linux/amd64)..."
mkdir -p "${BUILD_DIR}"

pushd "${PROJECT_ROOT}" > /dev/null
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build \
  -ldflags="-s -w" \
  -o "${BUILD_DIR}/${BINARY_NAME}" \
  ./...
popd > /dev/null

BINARY_SIZE=$(du -sh "${BUILD_DIR}/${BINARY_NAME}" | cut -f1)
echo "      Binary: ${BUILD_DIR}/${BINARY_NAME} (${BINARY_SIZE})"

# ── 2. Write environment file ─────────────────────────────────────────────────
echo "[2/6] Writing app environment file..."
cat > "${BUILD_DIR}/ubertool.env" <<EOF
# Ubertool API — Runtime Environment
# Generated by 04_deploy.sh — update config.env to change these values

APP_ENV=production
GRPC_PORT=${GRPC_PORT}

# Database
DB_HOST=${RDS_HOST}
DB_PORT=5432
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME}
DB_SSLMODE=require

# TLS
TLS_CERT=/etc/ubertool/certs/fullchain.pem
TLS_KEY=/etc/ubertool/certs/privkey.pem
EOF

# ── 3. Upload binary and env file to EC2 ──────────────────────────────────────
echo "[3/6] Uploading binary and config to EC2..."
scp -i "${SSH_KEY_PATH}" \
    -o StrictHostKeyChecking=no \
    "${BUILD_DIR}/${BINARY_NAME}" \
    "${BUILD_DIR}/ubertool.env" \
    "${SCRIPT_DIR}/ubertool-api.service" \
    "ubuntu@${ELASTIC_IP}:/tmp/"

# ── 4. Install on EC2 ─────────────────────────────────────────────────────────
echo "[4/6] Installing binary and service on EC2..."
ssh -i "${SSH_KEY_PATH}" \
    -o StrictHostKeyChecking=no \
    "ubuntu@${ELASTIC_IP}" \
    "
set -euo pipefail

# Create app user if it doesn't exist
sudo id -u ubertool &>/dev/null || sudo useradd -r -s /bin/false ubertool

# Install binary
sudo mv /tmp/${BINARY_NAME} /usr/local/bin/${BINARY_NAME}
sudo chmod 755 /usr/local/bin/${BINARY_NAME}
sudo chown ubertool:ubertool /usr/local/bin/${BINARY_NAME}

# Install environment file (owned by root, readable by ubertool)
sudo mv /tmp/ubertool.env /etc/ubertool/ubertool.env
sudo chown root:ubertool /etc/ubertool/ubertool.env
sudo chmod 640 /etc/ubertool/ubertool.env

# Fix cert permissions for ubertool user
sudo chown root:ubertool /etc/ubertool/certs/privkey.pem
sudo chmod 640 /etc/ubertool/certs/privkey.pem

# Install systemd service
sudo mv /tmp/ubertool-api.service /etc/systemd/system/ubertool-api.service
sudo systemctl daemon-reload
sudo systemctl enable ubertool-api

echo 'Installation complete.'
"

# ── 5. (Re)start service ──────────────────────────────────────────────────────
echo "[5/6] Restarting ubertool-api service..."
ssh -i "${SSH_KEY_PATH}" \
    -o StrictHostKeyChecking=no \
    "ubuntu@${ELASTIC_IP}" \
    "sudo systemctl restart ubertool-api && sleep 2 && sudo systemctl status ubertool-api --no-pager"

# ── 6. Health check ───────────────────────────────────────────────────────────
echo "[6/6] Service status check..."
ssh -i "${SSH_KEY_PATH}" \
    -o StrictHostKeyChecking=no \
    "ubuntu@${ELASTIC_IP}" \
    "sudo journalctl -u ubertool-api -n 20 --no-pager"

echo ""
echo "========================================"
echo " Deployment Complete!"
echo "========================================"
echo ""
echo "  gRPC endpoint : ${DOMAIN}:${GRPC_PORT}"
echo "  TLS           : Let's Encrypt (trusted by Android & iOS)"
echo ""
echo "  Logs  : ssh -i ${SSH_KEY_PATH} ubuntu@${ELASTIC_IP}"
echo "            sudo journalctl -u ubertool-api -f"
echo ""
echo "  To redeploy: just run ./04_deploy.sh again"
